# Alert drawing priority, colors, hazard category groupings, and WFO map.

# Priority: 1 = HIGHEST (Draws on Top), 101 = LOWEST (Draws on Bottom)
ALERT_PRIORITY = {
    "Tsunami Warning": 1,
    "Tornado Warning": 2,
    "Extreme Wind Warning": 3,
    "Severe Thunderstorm Warning": 4,
    "Flash Flood Warning": 5,
    "Flash Flood Statement": 6,
    "Severe Weather Statement": 7,
    "Civil Danger Warning": 8,
    "Radiological Hazard Warning": 9,
    "Hazardous Materials Warning": 10,
    "Fire Warning": 11,
    "Storm Surge Warning": 12,
    "Hurricane Force Wind Warning": 13,
    "Hurricane Warning": 14,
    "Typhoon Warning": 15,
    "Special Marine Warning": 16,
    "Blizzard Warning": 17,
    "Snow Squall Warning": 18,
    "Ice Storm Warning": 19,
    "Heavy Freezing Spray Warning": 20,
    "Winter Storm Warning": 21,
    "Lake Effect Snow Warning": 22,
    "Dust Storm Warning": 23,
    "Blowing Dust Warning": 24,
    "High Wind Warning": 25,
    "Tropical Storm Warning": 26,
    "Storm Warning": 27,
    "Tsunami Advisory": 28,
    "Tsunami Watch": 29,
    "Avalanche Warning": 30,
    "Earthquake Warning": 31,
    "Volcano Warning": 32,
    "Ashfall Warning": 33,
    "Flood Warning": 34,
    "Coastal Flood Warning": 35,
    "Lakeshore Flood Warning": 36,
    "Ashfall Advisory": 37,
    "High Surf Warning": 38,
    "Extreme Heat Warning": 39,
    "Tornado Watch": 40,
    "Severe Thunderstorm Watch": 41,
    "Flash Flood Watch": 42,
    "Gale Warning": 43,
    "Flood Statement": 44,
    "Extreme Cold Warning": 45,
    "Freeze Warning": 46,
    "Red Flag Warning": 47,
    "Storm Surge Watch": 48,
    "Hurricane Watch": 49,
    "Hurricane Force Wind Watch": 50,
    "Typhoon Watch": 51,
    "Tropical Storm Watch": 52,
    "Storm Watch": 53,
    "Tropical Cyclone Local Statement": 54,
    "Winter Weather Advisory": 55,
    "Avalanche Advisory": 56,
    "Cold Weather Advisory": 57,
    "Heat Advisory": 58,
    "Flood Advisory": 59,
    "Coastal Flood Advisory": 60,
    "Lakeshore Flood Advisory": 61,
    "High Surf Advisory": 62,
    "Dense Fog Advisory": 63,
    "Dense Smoke Advisory": 64,
    "Small Craft Advisory": 65,
    "Brisk Wind Advisory": 66,
    "Hazardous Seas Warning": 67,
    "Dust Advisory": 68,
    "Blowing Dust Advisory": 69,
    "Lake Wind Advisory": 70,
    "Wind Advisory": 71,
    "Frost Advisory": 72,
    "Freezing Fog Advisory": 73,
    "Freezing Spray Advisory": 74,
    "Low Water Advisory": 75,
    "Local Area Emergency": 76,
    "Winter Storm Watch": 77,
    "Rip Current Statement": 78,
    "Beach Hazards Statement": 79,
    "Gale Watch": 80,
    "Avalanche Watch": 81,
    "Hazardous Seas Watch": 82,
    "Heavy Freezing Spray Watch": 83,
    "Flood Watch": 84,
    "Coastal Flood Watch": 85,
    "Lakeshore Flood Watch": 86,
    "High Wind Watch": 87,
    "Extreme Heat Watch": 88,
    "Extreme Cold Watch": 89,
    "Freeze Watch": 90,
    "Fire Weather Watch": 91,
    "Extreme Fire Danger": 92,
    "Coastal Flood Statement": 93,
    "Lakeshore Flood Statement": 94,
    "Special Weather Statement": 95,
    "Marine Weather Statement": 96,
    "Air Quality Alert": 97,
    "Air Stagnation Advisory": 98,
    "Hazardous Weather Outlook": 99,
    "Hydrologic Outlook": 100,
    "Short Term Forecast": 101,
}

ALERT_COLORS = {
    "Tsunami Warning": "#FD6347",
    "Tornado Warning": "#FF0000",
    "Extreme Wind Warning": "#FF8C00",
    "Severe Thunderstorm Warning": "#FFA500",
    "Flash Flood Warning": "#8B0000",
    "Flash Flood Statement": "#8B0000",
    "Severe Weather Statement": "#00FFFF",
    "Civil Danger Warning": "#FFB6C1",
    "Radiological Hazard Warning": "#4B0082",
    "Hazardous Materials Warning": "#4B0082",
    "Fire Warning": "#A0522D",
    "Storm Surge Warning": "#B524F7",
    "Hurricane Force Wind Warning": "#CD5C5C",
    "Hurricane Warning": "#DC143C",
    "Typhoon Warning": "#DC143C",
    "Special Marine Warning": "#FFA500",
    "Blizzard Warning": "#FF4500",
    "Snow Squall Warning": "#C71585",
    "Ice Storm Warning": "#8B008B",
    "Heavy Freezing Spray Warning": "#00BFFF",
    "Winter Storm Warning": "#FF69B4",
    "Lake Effect Snow Warning": "#008B8B",
    "Dust Storm Warning": "#FFE4C4",
    "Blowing Dust Warning": "#FFE4C4",
    "High Wind Warning": "#DAA520",
    "Tropical Storm Warning": "#B22222",
    "Storm Warning": "#9400D3",
    "Tsunami Advisory": "#D2691E",
    "Tsunami Watch": "#FF00FF",
    "Avalanche Warning": "#1E90FF",
    "Earthquake Warning": "#8B4513",
    "Volcano Warning": "#2F4F4F",
    "Ashfall Warning": "#A9A9A9",
    "Flood Warning": "#00FF00",
    "Coastal Flood Warning": "#228B22",
    "Lakeshore Flood Warning": "#228B22",
    "Ashfall Advisory": "#696969",
    "High Surf Warning": "#228B22",
    "Extreme Heat Warning": "#C71585",
    "Tornado Watch": "#FFFF00",
    "Severe Thunderstorm Watch": "#DB7093",
    "Flash Flood Watch": "#2E8B57",
    "Gale Warning": "#DDA0DD",
    "Flood Statement": "#00FF00",
    "Extreme Cold Warning": "#0000FF",
    "Freeze Warning": "#483D8B",
    "Red Flag Warning": "#FF1493",
    "Storm Surge Watch": "#DB7FF7",
    "Hurricane Watch": "#FF00FF",
    "Hurricane Force Wind Watch": "#9932CC",
    "Typhoon Watch": "#FF00FF",
    "Tropical Storm Watch": "#F08080",
    "Storm Watch": "#FFE4B5",
    "Tropical Cyclone Local Statement": "#FFE4B5",
    "Winter Weather Advisory": "#7B68EE",
    "Avalanche Advisory": "#CD853F",
    "Cold Weather Advisory": "#AFEEEE",
    "Heat Advisory": "#FF7F50",
    "Flood Advisory": "#00FF7F",
    "Coastal Flood Advisory": "#7CFC00",
    "Lakeshore Flood Advisory": "#7CFC00",
    "High Surf Advisory": "#BA55D3",
    "Dense Fog Advisory": "#708090",
    "Dense Smoke Advisory": "#F0E68C",
    "Small Craft Advisory": "#D8BFD8",
    "Brisk Wind Advisory": "#D8BFD8",
    "Hazardous Seas Warning": "#D8BFD8",
    "Dust Advisory": "#BDB76B",
    "Blowing Dust Advisory": "#BDB76B",
    "Lake Wind Advisory": "#D2B48C",
    "Wind Advisory": "#D2B48C",
    "Frost Advisory": "#6495ED",
    "Freezing Fog Advisory": "#008080",
    "Freezing Spray Advisory": "#00BFFF",
    "Low Water Advisory": "#A52A2A",
    "Local Area Emergency": "#C0C0C0",
    "Winter Storm Watch": "#4682B4",
    "Rip Current Statement": "#40E0D0",
    "Beach Hazards Statement": "#40E0D0",
    "Gale Watch": "#FFC0CB",
    "Avalanche Watch": "#F4A460",
    "Hazardous Seas Watch": "#483D8B",
    "Heavy Freezing Spray Watch": "#BC8F8F",
    "Flood Watch": "#2E8B57",
    "Coastal Flood Watch": "#66CDAA",
    "Lakeshore Flood Watch": "#66CDAA",
    "High Wind Watch": "#B8860B",
    "Extreme Heat Watch": "#800000",
    "Extreme Cold Watch": "#5F9EA0",
    "Freeze Watch": "#00FFFF",
    "Fire Weather Watch": "#FFDEAD",
    "Extreme Fire Danger": "#E9967A",
    "Coastal Flood Statement": "#6B8E23",
    "Lakeshore Flood Statement": "#6B8E23",
    "Special Weather Statement": "#FFE4B5",
    "Marine Weather Statement": "#FFDAB9",
    "Air Quality Alert": "#808080",
    "Air Stagnation Advisory": "#808080",
    "Hazardous Weather Outlook": "#EEE8AA",
    "Hydrologic Outlook": "#90EE90",
    "Short Term Forecast": "#98FB98",
    # VTEC-derived events not in original NWS list
    "Wind Chill Warning": "#5F9EA0",
    "Wind Chill Watch": "#5F9EA0",
    "Wind Chill Advisory": "#AFEEEE",
    "Hard Freeze Warning": "#9400D3",
    "Hard Freeze Watch": "#4169E1",
    "Freezing Rain Advisory": "#DA70D6",
    "Sleet Warning": "#EE82EE",
    "Sleet Advisory": "#DDA0DD",
    "Ice Storm Watch": "#48D1CC",
    "Heat Warning": "#C71585",
}

DEFAULT_COLOR = "#C0C0C0"

HAZARD_CATEGORIES = {
    "All Alerts": None,
    "Severe Weather Alerts": [
        "Tornado Warning",
        "Severe Thunderstorm Warning",
        "Flash Flood Warning",
        "Tornado Watch",
        "Severe Thunderstorm Watch",
        "Extreme Wind Warning",
        "Severe Weather Statement",
    ],
    "Severe Weather Warnings": [
        "Tornado Warning",
        "Severe Thunderstorm Warning",
        "Flash Flood Warning",
        "Severe Weather Statement",
        "Special Marine Warning",
    ],
    "Severe Weather Watches": [
        "Tornado Watch",
        "Severe Thunderstorm Watch",
        "Flash Flood Watch",
    ],
    "Hydrology Alerts": [
        "Flash Flood Warning",
        "Flood Warning",
        "Flash Flood Watch",
        "Flood Watch",
        "Flood Advisory",
        "Flash Flood Statement",
        "Flood Statement",
        "Hydrologic Outlook",
        "Coastal Flood Statement",
        "Lakeshore Flood Advisory",
        "Lakeshore Flood Statement",
        "Lakeshore Flood Warning",
        "Lakeshore Flood Watch",
    ],
    "Flash Flood Alerts": [
        "Flash Flood Warning",
        "Flash Flood Watch",
        "Flash Flood Statement",
    ],
    "Winter Alerts": [
        "Winter Storm Warning",
        "Blizzard Warning",
        "Ice Storm Warning",
        "Winter Weather Advisory",
        "Winter Storm Watch",
        "Lake Effect Snow Warning",
        "Snow Squall Warning",
        "Freeze Warning",
        "Freeze Watch",
        "Frost Advisory",
        "Extreme Cold Warning",
        "Extreme Cold Watch",
        "Heavy Freezing Spray Warning",
        "Avalanche Advisory",
        "Avalanche Watch",
        "Avalanche Warning",
        "Freezing Fog Advisory",
        "Heavy Freezing Spray Watch",
    ],
    "Cold Alerts": [
        "Extreme Cold Warning",
        "Extreme Cold Watch",
        "Freeze Warning",
        "Freeze Watch",
        "Frost Advisory",
        "Cold Weather Advisory",
    ],
    "Fire Alerts": [
        "Red Flag Warning",
        "Fire Weather Watch",
        "Extreme Fire Danger",
        "Fire Warning",
    ],
    "Heat Alerts": [
        "Heat Advisory",
        "Extreme Heat Warning",
        "Extreme Heat Watch",
    ],
    "Coastal Alerts": [
        "Coastal Flood Warning",
        "Coastal Flood Watch",
        "Coastal Flood Advisory",
        "High Surf Warning",
        "High Surf Advisory",
        "Rip Current Statement",
        "Storm Surge Warning",
        "Storm Surge Watch",
        "Beach Hazards Statement",
    ],
    "Marine Alerts": [
        "Special Marine Warning",
        "Marine Weather Statement",
        "Gale Warning",
        "Gale Watch",
        "Hurricane Force Wind Warning",
        "Storm Warning",
        "Small Craft Advisory",
        "Hazardous Seas Warning",
        "Hazardous Seas Watch",
        "Heavy Freezing Spray Warning",
        "Brisk Wind Advisory",
        "Freezing Spray Advisory",
        "Low Water Advisory",
        "Storm Watch",
    ],
    "Tropical Cyclone Alerts": [
        "Hurricane Warning",
        "Hurricane Watch",
        "Tropical Storm Warning",
        "Tropical Storm Watch",
        "Storm Surge Warning",
        "Storm Surge Watch",
        "Extreme Wind Warning",
        "Tropical Cyclone Local Statement",
        "Hurricane Force Wind Warning",
        "Hurricane Force Wind Watch",
        "Typhoon Warning",
        "Typhoon Watch",
    ],
    "Non-Precipitation Alerts": [
        "High Wind Warning",
        "High Wind Watch",
        "Wind Advisory",
        "Dense Fog Advisory",
        "Dense Smoke Advisory",
        "Dust Storm Warning",
        "Blowing Dust Advisory",
        "Air Quality Alert",
        "Ashfall Warning",
        "Ashfall Advisory",
        "Air Stagnation Advisory",
        "Blowing Dust Warning",
        "Dust Advisory",
        "Lake Wind Advisory",
    ],
    "Geophysical Alerts": [
        "Earthquake Warning",
        "Tsunami Advisory",
        "Tsunami Watch",
        "Tsunami Warning",
        "Volcano Warning",
    ],
    "Public Safety Alerts": [
        "Civil Danger Warning",
        "Hazardous Materials Warning",
        "Local Area Emergency",
        "Radiological Hazard Warning",
    ],
    "Informational Alerts": [
        "Hazardous Weather Outlook",
        "Short Term Forecast",
        "Special Weather Statement",
    ],
}

# Backward-compatible aliases used by older UI labels/localStorage values.
HAZARD_CATEGORY_ALIASES = {
    "All Hazards & Warnings": "All Alerts",
    "Hydrology Hazards": "Hydrology Alerts",
    "Flash Flood Hazards": "Flash Flood Alerts",
    "Winter Hazards": "Winter Alerts",
    "Cold Hazards": "Cold Alerts",
    "Fire Hazards": "Fire Alerts",
    "Heat Hazards": "Heat Alerts",
    "Coastal Hazards": "Coastal Alerts",
    "Marine Hazards": "Marine Alerts",
    "Non-Precipitation Hazards": "Non-Precipitation Alerts",
    "All Hydrology Hazards": "Hydrology Alerts",
    "Extreme Cold Hazards": "Cold Alerts",
    "Geophysical Hazards": "Geophysical Alerts",
    "Public Safety Hazards": "Public Safety Alerts",
    "Informational Hazards": "Informational Alerts",
}

NWS_WFO_MAP = {
    "All WFOs (No Filter)": None,
    "Wakefield, VA": "AKQ",
    "Blacksburg, VA": "RNK",
    "Sterling, VA (DC)": "LWX",
    "Morehead City, NC": "MHX",
    "Raleigh, NC": "RAH",
    "Wilmington, NC": "ILM",
    "Columbia, SC": "CAE",
    "Charleston, SC": "CHS",
    "Greenville-Spartanburg, SC": "GSP",
    "Philadelphia, PA": "PHI",
    "State College, PA": "CTP",
    "Pittsburgh, PA": "PBZ",
    "New York City, NY": "OKX",
    "Albany, NY": "ALY",
    "Buffalo, NY": "BUF",
    "Binghamton, NY": "BGM",
    "Boston, MA": "BOX",
    "Caribou, ME": "CAR",
    "Gray/Portland, ME": "GYX",
    "Burlington, VT": "BTV",
    "Cleveland, OH": "CLE",
    "Wilmington, OH": "ILN",
    "Charleston, WV": "RLX",
    "Atlanta, GA": "FFC",
    "Tallahassee, FL": "TAE",
    "Jacksonville, FL": "JAX",
    "Melbourne, FL": "MLB",
    "Miami, FL": "MFL",
    "Tampa Bay, FL": "TBW",
    "Key West, FL": "KEY",
    "Birmingham, AL": "BMX",
    "Huntsville, AL": "HUN",
    "Mobile, AL": "MOB",
    "Jackson, MS": "JAN",
    "New Orleans, LA": "LIX",
    "Lake Charles, LA": "LCH",
    "Shreveport, LA": "SHV",
    "Nashville, TN": "OHX",
    "Memphis, TN": "MEG",
    "Morristown, TN": "MRX",
    "Little Rock, AR": "LZK",
    "Tulsa, OK": "TSA",
    "Oklahoma City, OK": "OUN",
    "Fort Worth, TX": "FWD",
    "Houston, TX": "HGX",
    "Austin/San Antonio, TX": "EWX",
    "Corpus Christi, TX": "CRP",
    "Brownsville, TX": "BRO",
    "Lubbock, TX": "LUB",
    "Amarillo, TX": "AMA",
    "Midland, TX": "MAF",
    "San Angelo, TX": "SJT",
    "El Paso, TX": "EPZ",
    "Albuquerque, NM": "ABQ",
    "Chicago, IL": "LOT",
    "Lincoln, IL": "ILX",
    "St. Louis, MO": "LSX",
    "Kansas City, MO": "EAX",
    "Springfield, MO": "SGF",
    "Indianapolis, IN": "IND",
    "Northern Indiana": "IWX",
    "Louisville, KY": "LMK",
    "Paducah, KY": "PAH",
    "Jackson, KY": "JKL",
    "Detroit, MI": "DTX",
    "Grand Rapids, MI": "GRR",
    "Gaylord, MI": "APX",
    "Marquette, MI": "MQT",
    "Milwaukee, WI": "MKX",
    "Green Bay, WI": "GRB",
    "La Crosse, WI": "ARX",
    "Minneapolis, MN": "MPX",
    "Duluth, MN": "DLH",
    "Des Moines, IA": "DMX",
    "Quad Cities, IA": "DVN",
    "Sioux Falls, SD": "FSD",
    "Rapid City, SD": "UNR",
    "Aberdeen, SD": "ABR",
    "Bismarck, ND": "BIS",
    "Grand Forks, ND": "FGF",
    "Omaha, NE": "OAX",
    "Hastings, NE": "GID",
    "North Platte, NE": "LBF",
    "Wichita, KS": "ICT",
    "Topeka, KS": "TOP",
    "Dodge City, KS": "DDC",
    "Goodland, KS": "GLD",
    "Denver/Boulder, CO": "BOU",
    "Pueblo, CO": "PUB",
    "Grand Junction, CO": "GJT",
    "Cheyenne, WY": "CYS",
    "Riverton, WY": "RIW",
    "Seattle, WA": "SEW",
    "Spokane, WA": "OTX",
    "Portland, OR": "PQR",
    "Medford, OR": "MFR",
    "Pendleton, OR": "PDT",
    "Boise, ID": "BOI",
    "Pocatello, ID": "PIH",
    "Great Falls, MT": "TFX",
    "Billings, MT": "BYZ",
    "Missoula, MT": "MSO",
    "Glasgow, MT": "GGW",
    "Salt Lake City, UT": "SLC",
    "Reno, NV": "REV",
    "Las Vegas, NV": "VEF",
    "Elko, NV": "LKN",
    "Phoenix, AZ": "PSR",
    "Tucson, AZ": "TWC",
    "Flagstaff, AZ": "FGZ",
    "San Diego, CA": "SGX",
    "Los Angeles, CA": "LOX",
    "San Francisco, CA": "MTR",
    "Sacramento, CA": "STO",
    "Eureka, CA": "EKA",
    "Hanford, CA": "HNX",
}

# ============================================================================
# Geometry Optimization Configuration (Phase 1)
# ============================================================================
# Events excluded from geometry simplification. These must always use full
# geometry at every zoom level for display and interaction.
GEOMETRY_EXCLUDED_EVENTS = {
    "Tornado Warning",
    "Severe Thunderstorm Warning",
    "Flash Flood Warning",
    "Special Marine Warning",
    "Snow Squall Warning",
}

# Simplification parameters for low-zoom rendering of non-excluded events.
# Controls topological simplification of polygon geometries.
GEOMETRY_SIMPLIFICATION_SETTINGS = {
    # Tolerance in meters for Douglas-Peucker simplification algorithm
    "low_zoom_tolerance_m": 1000.0,
    # Minimum number of vertices to preserve during simplification
    "minimum_vertices_gate": 3,
    # Whether to preserve topology during simplification (prevents self-intersections)
    "preserve_topology": True,
}

# Endpoint parameters and defaults for geometry serving.
# geometry_mode: "full" for canonical geometry, "display" for simplified low-zoom variant
# zoom_bucket: "low" for CONUS-like zoom, "high" for state/local zoom
GEOMETRY_ENDPOINT_DEFAULTS = {
    "geometry_mode": "full",  # Default to full geometry for backward compatibility
    "zoom_bucket": "high",  # Default to high zoom (no simplification)
}
